# Generated by Django 3.2.5 on 2022-01-24 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('slug', models.SlugField(max_length=250)),
                ('name', models.CharField(max_length=150)),
                ('age', models.IntegerField()),
                ('dni', models.CharField(max_length=15)),
                ('phone', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Pets',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('slug', models.SlugField(max_length=250)),
                ('age', models.IntegerField()),
                ('name', models.CharField(max_length=150)),
                ('species', models.CharField(max_length=150)),
                ('sex', models.CharField(max_length=10)),
            ],
        ),
    ]
